[package]
name = "i2d_tree"
version = "0.1.0"
authors = ["Mark Shevchenko"]
edition = "2018"

[dependencies]
approx = "0.4.0"
rand = "0.8.4"
rand_pcg = "0.3.1"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "build_tree"
harness = false