[package]
name = "tests"
version = "0.1.0"
authors = ["Mark Shevchenko"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
i2d_tree = { path = "../i2d_tree" }